### PR TITLE
Distribute ES5, not ES6

### PR DESCRIPTION
**Pull request by Borzik**
ES5 should be distributed for wider support.
Implemented according to [this article](https://booker.codes/how-to-build-and-publish-es6-npm-modules-today-with-babel/)

### CODE REVIEW

**Comment by cscalfani** [comment]
Thanks for the pull request, but I'm not interested in supporting old browsers.

**Comment by Borzik** [comment]
@cscalfani this is not to support old browsers, the main reason is to support [uglify-js](https://www.npmjs.com/package/uglify-js), and its dependencies. Could you please review your decision? Right now projects which utilize `uglify-js` (which is quite popular with 22 millions downloads per month) cannot be built without errors if some of their dependencies use ES6 and don't provide ES5 version.

**Comment by cscalfani** [comment]
Why not use [uglify-es](https://github.com/mishoo/UglifyJS2/tree/harmony)?

**Comment by Borzik** [comment]
For example, Vue CLI uses `uglify-js`, and rewriting complete configuration (or making babel compile node_modules) doesn't worth the effort - it's easier for me to keep my fork then (luckily this lib in stable state and my fork won't require maintenance at all).
The same can be said about `create-react-app`, see [this issue in their repo](https://github.com/facebookincubator/create-react-app/issues/1125)
> We don't recommend using libraries that don't precompile their code to ES5 but are supposed to be usable in ES5.

**Comment by cscalfani** [comment]
I think keeping your fork makes the most sense. My personal philosophy is that one should try to move forward as soon as is reasonable. ES6 is pretty widely supported and I'm surprised there isn't support for it in Vue which is a fairly new framework.

Best of luck.

**Comment by gaearon** [comment]
FYI, we're starting the work to compile deps with `babel-preset-env` in Create React App: https://github.com/facebookincubator/create-react-app/pull/3776

Let us know if you have feedback about how this should work.

**Comment by gaearon** [comment]
This shipped in 2.0.
https://reactjs.org/blog/2018/10/01/create-react-app-v2.html

**Pull request closed without merging**
